---
output: github_document
---

<!-- README.md is generated from README.Rmd. Please edit that file -->

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>",
  fig.path = "man/figures/README-",
  out.width = "100%"
)
```

# farr

<!-- badges: start -->
<!-- badges: end -->

The goal of farr is to ...

## Installation

You can install the released version of farr from [CRAN](https://CRAN.R-project.org) with:

``` r
install.packages("farr")
```

And the development version from [GitHub](https://github.com/) with:

``` r
# install.packages("devtools")
devtools::install_github("iangow/farr")
```
## Example

This is a basic example which shows you how to solve a common problem:

```{r example}
library(farr)
library(dplyr, warn.conflicts = FALSE)
library(DBI)

pg <- dbConnect(RPostgres::Postgres(), bigint = "integer", sslmode='require')

url <- "https://github.com/tidyverse/dbplyr/files/6239289/temp.RDS.zip"
t <- tempfile(fileext = ".zip")
download.file(url, t)
temp <- as_tibble(readRDS(unzip(t)))
unlink("temp.RDS")

temp2 <- dbplyr::copy_inline(pg, temp)

temp

temp2
```
